# Sets default memory used for gradle commands.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Minecraft / Forge 버전 정보
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.2.0
forge_version_range=[47,)
loader_version_range=[47,)

# 모드 정보
mod_id=chronobreaker
mod_name=ChronoBreaker
mod_license=All Rights Reserved
mod_version=1.0.0
mod_group_id=com.zzt.chronobreaker
mod_authors=zzt
mod_description=시간을 다루는 마인크래프트 모드 - 몬스터의 시간을 빼앗아 시간을 조종하는 스킬을 사용하세요.
